/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ProdutoMsl;
import bean.ProdutoVendaMsl;
import dao.ClienteDAO;
import dao.ProdutoDAO;
import java.util.ArrayList;
import java.util.List;
import tools.UtilMsl;
import view.JDlgVendas;
import viewControle.ProdutoVendaControle;

/**
 *
 * @author Sebas
 */
public class JDlgVendasProdutos extends javax.swing.JDialog {

    JDlgVendas jDlgVendas;
    public ProdutoVendaControle produtoVendaControle;
    ProdutoDAO produtoDAO;

    /**
     * Creates new form JDlgInclusaoVendas
     */
    public JDlgVendasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        produtoVendaControle = new ProdutoVendaControle();
        produtoDAO = new ProdutoDAO();

        UtilMsl.habilitar(false, jTxtTotalMsl);

        ProdutoDAO produtoDAO = new ProdutoDAO();
        List lista = new ArrayList();
        List listaProdutos = produtoDAO.listAll();
        for (int i = 0; i < listaProdutos.size(); i++) {
            jCboProdutoMsl.addItem((ProdutoMsl) listaProdutos.get(i));
        }

    }

    public ProdutoVendaMsl viewBean() {
        ProdutoVendaMsl produtovendaMsl = new ProdutoVendaMsl();
        int quantidadeMsl = UtilMsl.strInt(jTxtQuantidadeMsl.getText());
        double totalMsl = UtilMsl.strDouble(jTxtTotalMsl.getText());
        produtovendaMsl.setProdutoMsl((ProdutoMsl) jCboProdutoMsl.getSelectedItem());

        return produtovendaMsl;
    }

    public void beanView(ProdutoVendaMsl produtoVendaMsl) {
        String intStr = UtilMsl.intStr(produtoVendaMsl.getQuantidadeMsl());
        String totalMsl = UtilMsl.doubleStr(produtoVendaMsl.getValorUnitarioMsl());
        jCboProdutoMsl.setSelectedItem(produtoVendaMsl.getProdutoMsl());

    }

    public void setTelaAnterior(JDlgVendas jDlgVendas) {
        this.jDlgVendas = jDlgVendas;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboProdutoMsl = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtQuantidadeMsl = new javax.swing.JTextField();
        jTxtValorUnitarioMsl = new javax.swing.JTextField();
        jTxtTotalMsl = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produto");

        jCboProdutoMsl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutoMslItemStateChanged(evt);
            }
        });
        jCboProdutoMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboProdutoMslActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitario");

        jLabel4.setText("Total");

        jTxtQuantidadeMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeMslActionPerformed(evt);
            }
        });
        jTxtQuantidadeMsl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeMslKeyReleased(evt);
            }
        });

        jTxtValorUnitarioMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtValorUnitarioMslActionPerformed(evt);
            }
        });

        jTxtTotalMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalMslActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboProdutoMsl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtQuantidadeMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtValorUnitarioMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTotalMsl)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboProdutoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtQuantidadeMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtValorUnitarioMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTotalMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboProdutoMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboProdutoMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboProdutoMslActionPerformed

    private void jCboProdutoMslItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutoMslItemStateChanged
        if (jCboProdutoMsl.getSelectedIndex() != -1) {
            jTxtQuantidadeMsl.setText("1");
            ProdutoMsl produtoMsl = (ProdutoMsl) jCboProdutoMsl.getSelectedItem();
            jTxtValorUnitarioMsl.setText(UtilMsl.doubleStr(produtoMsl.getPrecoMsl()));

        }
    }//GEN-LAST:event_jCboProdutoMslItemStateChanged

    private void jTxtValorUnitarioMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtValorUnitarioMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtValorUnitarioMslActionPerformed

    private void jTxtQuantidadeMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeMslActionPerformed

    private void jTxtQuantidadeMslKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeMslKeyReleased
        if (jTxtQuantidadeMsl.getText().isEmpty() == false) {
            double unitario = UtilMsl.strDouble(jTxtValorUnitarioMsl.getText());
            int quantidade = UtilMsl.strInt(jTxtQuantidadeMsl.getText());
            jTxtTotalMsl.setText(String.valueOf(quantidade * unitario));
        } else {
            jTxtTotalMsl.setText("0");
        }
    }//GEN-LAST:event_jTxtQuantidadeMslKeyReleased

    private void jTxtTotalMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalMslActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UtilMsl.mensagem("Operacao cancelada");
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ProdutoVendaMsl produtovendaMsl = new ProdutoVendaMsl();// Criação de um novo objeto ProdutoVendaMsl para representar um produto vendido
        ProdutoVendaControle vendas = new ProdutoVendaControle();// Criação de um controle de vendas de produtos
        produtovendaMsl.setProdutoMsl((ProdutoMsl) jCboProdutoMsl.getSelectedItem());// Define o produto selecionado no ComboBox na instância de ProdutoVendaMsl
        produtovendaMsl.setQuantidadeMsl(UtilMsl.strInt(jTxtQuantidadeMsl.getText()));// Converte o valor da quantidade (String) do campo de texto para inteiro e define a quantidade do produto vendido
        produtovendaMsl.setValorUnitarioMsl((int) UtilMsl.strDouble(jTxtValorUnitarioMsl.getText()));// Converte o valor unitário do produto (String) para double e o define como valor unitário na instância de ProdutoVendaMsl
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {// Verifica se o título da janela (getTitle()) começa com a letra "I" (indicando que está inserindo um novo item)
            jDlgVendas.produtoVendaControle.addBean(produtovendaMsl);    // Adiciona o novo produto à lista de produtos controlada pelo diálogo de vendas
        } else {// Atualiza o produto selecionado na lista com os novos valores
            jDlgVendas.produtoVendaControle.updateBean(jDlgVendas.getSelectedRowProd(), produtovendaMsl);
        }


        UtilMsl.limparCampos(jTxtQuantidadeMsl);// Limpa o campo de quantidade após a inserção ou atualização do produto


        setVisible(false);// Fecha a janela de diálogo, tornando-a invisível

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendasProdutos dialog = new JDlgVendasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<ProdutoMsl> jCboProdutoMsl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtQuantidadeMsl;
    private javax.swing.JTextField jTxtTotalMsl;
    private javax.swing.JTextField jTxtValorUnitarioMsl;
    // End of variables declaration//GEN-END:variables
}
