/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import bean.UsuariosMsl;
import dao.UsuariosDAO;
import tools.UtilMsl;
import viewPesquisa.JDlgUsuariosPesquisa;


/**
 *
 * @author Sebas0
 */
public class JDlgUsuarios extends javax.swing.JDialog {
 
    
        boolean incl;
    public boolean pesquisado;
    /**
     * Creates new form JDlgUsuariosNovoIA
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Usuarios");
        setLocationRelativeTo(null);



        
        
        UtilMsl.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
        jBtnIncluir.setEnabled(true);
        
        
    
    }
     public UsuariosMsl viewBean() {
        UsuariosMsl usuarios = new UsuariosMsl();
        
        
        usuarios.setIdusuariosMsl(UtilMsl.strInt(JTxtCodigoMsl.getText()));
        usuarios.setNomeMsl(JTxtNomeMsl.getText());
        
        usuarios.setDataNascMsl(null);//jFmtDataNascimento.getText();
        usuarios.setSexoMsl(jJtxtSexoMsl.getText());
        
        usuarios.setEmailMsl(JTxtEmailMsl.getText());
        usuarios.setSenhaMsl(jPwfSenhaMsl.getText());
        

        return usuarios;
    }
    
    
        public UsuariosMsl beanView(UsuariosMsl usuarios){
            
        JTxtCodigoMsl.setText(UtilMsl.intStr(usuarios.getIdusuariosMsl()));
        
        JTxtNomeMsl.setText(usuarios.getNomeMsl());
        
        
        jFmtDataMsl.setText(null);//cliente.getDataNascimento());
        
        jJtxtSexoMsl.setText(usuarios.getSexoMsl());
        JTxtEmailMsl.setText(usuarios.getEmailMsl());
        jFmtCpfMsl.setText(usuarios.getCpfMsl());
       
        jPwfSenhaMsl.setText(usuarios.getSenhaMsl());
        
      
        jBtnAlterar.setEnabled(true);
        return usuarios;
        }        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPwfSenhaMsl = new javax.swing.JPasswordField();
        JTxtCodigoMsl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxtNomeMsl = new javax.swing.JTextField();
        jFmtDataMsl = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTxtEmailMsl = new javax.swing.JFormattedTextField();
        jFmtCpfMsl = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jJtxtSexoMsl = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Blackadder ITC", 1, 36)); // NOI18N
        jLabel14.setText("Cadastro de Usuarios");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Excluir (1).png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pesquisa (1).png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jPwfSenhaMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwfSenhaMslActionPerformed(evt);
            }
        });

        JTxtCodigoMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtCodigoMslActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel6.setText("Data de Nascimento");

        jLabel5.setText("CPF");

        JTxtEmailMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtEmailMslActionPerformed(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel8.setText("Sexo");

        jLabel9.setText("Senha");

        jLabel1.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnAlterar)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnExcluir)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnConfirmar)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnCancelar)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(JTxtCodigoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFmtCpfMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(JTxtNomeMsl)
                            .addComponent(JTxtEmailMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jJtxtSexoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jPwfSenhaMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtCodigoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCpfMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jJtxtSexoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTxtNomeMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTxtEmailMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jFmtDataMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPwfSenhaMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        incl = true;
        UtilMsl.habilitar(true, jBtnConfirmar, jBtnCancelar, JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
        UtilMsl.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incl = false;
        UtilMsl.habilitar(true, jBtnConfirmar, jBtnCancelar,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
        UtilMsl.habilitar(false, jBtnIncluir,jBtnAlterar, jBtnExcluir, jBtnPesquisar, JTxtCodigoMsl);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
            
        
         if (UtilMsl.perguntar("Deseja excluir o registro") == true) {

            UsuariosMsl usuarios = viewBean();
            UsuariosDAO usuariosDAO = new UsuariosDAO();//executa o dao
            usuariosDAO.delete(usuarios);

        } else {

            UtilMsl.mensagem("Exclusão cancelada.");
        }
        
        
        
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed

               
          UsuariosMsl usuarios = viewBean();
        UsuariosDAO usuariosDAO = new UsuariosDAO();//executa o dao
        //boolean pra incluir ou alterar
        if(incl == true){
        usuariosDAO.insert(usuarios);
        
        }else{
        usuariosDAO.update(usuarios);
        }



        UtilMsl.habilitar(false, JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
        UtilMsl.habilitar(true, jBtnIncluir,jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed

        
        JDlgUsuariosPesquisa jDlgUsuariosPesquisa = new JDlgUsuariosPesquisa(null, true);
        jDlgUsuariosPesquisa.setTelaAnterior(this);
        jDlgUsuariosPesquisa.setVisible(true);
        
        UtilMsl.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnIncluir);
        UtilMsl.habilitar(false, jBtnCancelar, jBtnConfirmar);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        UtilMsl.mensagem("Operação Cancelada!");
        UtilMsl.habilitar(false, jBtnCancelar, jBtnConfirmar, jBtnAlterar, jBtnExcluir, JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
        UtilMsl.habilitar(true, jBtnIncluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,JTxtCodigoMsl,jFmtCpfMsl,JTxtNomeMsl,jFmtDataMsl,JTxtEmailMsl,jJtxtSexoMsl,jPwfSenhaMsl);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jPwfSenhaMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwfSenhaMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwfSenhaMslActionPerformed

    private void JTxtCodigoMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtCodigoMslActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JTxtCodigoMslActionPerformed

    private void JTxtEmailMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtEmailMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtEmailMslActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtCodigoMsl;
    private javax.swing.JFormattedTextField JTxtEmailMsl;
    private javax.swing.JTextField JTxtNomeMsl;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JFormattedTextField jFmtCpfMsl;
    private javax.swing.JFormattedTextField jFmtDataMsl;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jJtxtSexoMsl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwfSenhaMsl;
    // End of variables declaration//GEN-END:variables
}
