/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import bean.ClienteMsl;
import dao.ClienteDAO;
import tools.UtilMsl;
import viewPesquisa.JDlgClientePesquisa;


/**
 *
 * @author Sebas0
 */
public class JDlgCliente extends javax.swing.JDialog {
 
    
        boolean incl;
    public boolean pesquisado;
    /**
     * Creates new form JDlgUsuariosNovoIA
     */
    public JDlgCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cliente");
        setLocationRelativeTo(null);



        
        
        UtilMsl.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
        jBtnIncluir.setEnabled(true);
        
        
    
    }
     public ClienteMsl viewBean() {
        ClienteMsl cliente = new ClienteMsl();
        
        cliente.setIdclienteMsl(UtilMsl.strInt(jTxtCodigoMsl.getText()));
        
        cliente.setNomeMsl(jTxtNomeMsl.getText());
        cliente.setEmailMsl(JTxtEmailMsl.getText());
        cliente.setTelefoneMsl(jFmtTelefoneMsl.getText());
        cliente.setEstadoCivilMsl(jJtxtEstadoCivilMsl.getText());
        cliente.setProfissaoMsl(JTxtProfissaoMsl.getText());
        cliente.setRgMsl(jFmtRgMsl.getText());
        cliente.setCpfMsl(jFmtCpfMsl.getText());
        
        cliente.setDataNascMsl(null);//jFmtDataNascimento.getText();
        
        cliente.setEnderecoMsl(JTxtEnderecoMsl.getText());
        cliente.setEstadoMsl(JTxtEstadoMsl.getText());
        cliente.setCidadeMsl(JTxtCidadeMsl.getText());
        cliente.setCepMsl(jFmtCepMsl.getText());
        cliente.setFormacaoMsl(jJtxtFormacaoMsl.getText());
       
        

        return cliente;
    }
    
    
        public ClienteMsl beanView(ClienteMsl cliente){
            
        jTxtCodigoMsl.setText(UtilMsl.intStr(cliente.getIdclienteMsl()));
        
        jTxtNomeMsl.setText(cliente.getNomeMsl());
        JTxtEmailMsl.setText(cliente.getEmailMsl());
        jFmtTelefoneMsl.setText(cliente.getTelefoneMsl());
        jJtxtEstadoCivilMsl.setText(cliente.getEstadoCivilMsl());
        JTxtProfissaoMsl.setText(cliente.getProfissaoMsl());
        jFmtRgMsl.setText(cliente.getRgMsl());
        jFmtCpfMsl.setText(cliente.getCpfMsl());
        
        
        jFmtDataMsl.setText(null);//cliente.getDataNascimento());
        
        JTxtEnderecoMsl.setText(cliente.getEnderecoMsl());
        JTxtEstadoMsl.setText(cliente.getEstadoMsl());
        JTxtCidadeMsl.setText(cliente.getCidadeMsl());
        jFmtCepMsl.setText(cliente.getCepMsl());
        jJtxtFormacaoMsl.setText(cliente.getFormacaoMsl());

        
        
        
        jBtnAlterar.setEnabled(true);
        return cliente;
        }        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoMsl = new javax.swing.JTextField();
        jTxtNomeMsl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxtEmailMsl = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmtTelefoneMsl = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jJtxtFormacaoMsl = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmtRgMsl = new javax.swing.JFormattedTextField();
        jFmtCpfMsl = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTxtProfissaoMsl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JTxtEnderecoMsl = new javax.swing.JTextField();
        JTxtCidadeMsl = new javax.swing.JTextField();
        JTxtEstadoMsl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFmtCepMsl = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jFmtDataMsl = new javax.swing.JFormattedTextField();
        jJtxtEstadoCivilMsl = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Blackadder ITC", 1, 36)); // NOI18N
        jLabel14.setText("Cadastro de Cliente");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Excluir (1).png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ok .png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pesquisa (1).png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jTxtCodigoMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoMslActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        JTxtEmailMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtEmailMslActionPerformed(evt);
            }
        });

        jLabel7.setText("email");

        jFmtTelefoneMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtTelefoneMslActionPerformed(evt);
            }
        });

        jLabel16.setText("Formação");

        jJtxtFormacaoMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJtxtFormacaoMslActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone");

        jLabel5.setText("Profissao");

        jLabel6.setText("RG");

        jLabel8.setText("CPF");

        jLabel11.setText("Estado");

        jLabel12.setText("Cidade");

        jLabel10.setText("Endereço");

        jFmtCepMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCepMslActionPerformed(evt);
            }
        });

        jLabel13.setText("Cep");

        jLabel15.setText("Data de Nascimento");

        jFmtDataMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataMslActionPerformed(evt);
            }
        });

        jJtxtEstadoCivilMsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJtxtEstadoCivilMslActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado Civil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnAlterar)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnExcluir)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnConfirmar)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnCancelar)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTxtEnderecoMsl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(203, 203, 203)
                                        .addComponent(jLabel12))
                                    .addComponent(JTxtEstadoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(183, 183, 183))
                            .addComponent(JTxtCidadeMsl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtCodigoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtNomeMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtDataMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(158, 158, 158))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jFmtRgMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(132, 132, 132)
                                                .addComponent(jLabel5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jFmtCpfMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(JTxtProfissaoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jJtxtEstadoCivilMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(JTxtEmailMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jFmtTelefoneMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jJtxtFormacaoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFmtCepMsl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCodigoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtNomeMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5)
                                .addComponent(JTxtEmailMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25))
                            .addComponent(jFmtTelefoneMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(6, 6, 6)
                        .addComponent(jFmtDataMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(1, 1, 1)
                                .addComponent(jJtxtFormacaoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCepMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTxtProfissaoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCpfMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtRgMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jJtxtEstadoCivilMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTxtCidadeMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTxtEstadoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTxtEnderecoMsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        incl = true;
        UtilMsl.habilitar(true, jBtnConfirmar, jBtnCancelar, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
        UtilMsl.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incl = false;
        UtilMsl.habilitar(true, jBtnConfirmar, jBtnCancelar, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
        UtilMsl.habilitar(false, jBtnIncluir,jBtnAlterar, jBtnExcluir, jBtnPesquisar, jTxtCodigoMsl);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
            
        
         if (UtilMsl.perguntar("Deseja excluir o registro") == true) {

            ClienteMsl cliente = viewBean();
            ClienteDAO clienteDAO = new ClienteDAO();//executa o dao
            clienteDAO.delete(cliente);

        } else {

            UtilMsl.mensagem("Exclusão cancelada.");
        }
        
        
        
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed

               
        ClienteMsl cliente = viewBean();
        ClienteDAO clienteDAO = new ClienteDAO();//executa o dao
        //boolean pra incluir ou alterar
        if(incl == true){
        clienteDAO.insert(cliente);
        
        }else{
        clienteDAO.update(cliente);
        }



        UtilMsl.habilitar(false,  jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
        UtilMsl.habilitar(true, jBtnIncluir,jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed

        
        JDlgClientePesquisa jDlgClientePesquisa = new JDlgClientePesquisa(null, true);
        jDlgClientePesquisa.setTelaAnterior(this);
        jDlgClientePesquisa.setVisible(true);
        
        UtilMsl.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnIncluir);
        UtilMsl.habilitar(false, jBtnCancelar, jBtnConfirmar);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        UtilMsl.mensagem("Operação Cancelada!");
        UtilMsl.habilitar(false, jBtnCancelar, jBtnConfirmar, jBtnAlterar, jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
        UtilMsl.habilitar(true, jBtnIncluir, jBtnPesquisar);
        UtilMsl.limparCampos(jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir, jTxtCodigoMsl, jTxtNomeMsl, jFmtDataMsl, JTxtEmailMsl, jJtxtEstadoCivilMsl, jFmtCepMsl, JTxtProfissaoMsl, JTxtEnderecoMsl, JTxtEstadoMsl, JTxtCidadeMsl, jFmtTelefoneMsl, jFmtCpfMsl,jFmtRgMsl,jJtxtFormacaoMsl);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtCodigoMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoMslActionPerformed

    private void JTxtEmailMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtEmailMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtEmailMslActionPerformed

    private void jFmtTelefoneMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtTelefoneMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtTelefoneMslActionPerformed

    private void jJtxtFormacaoMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJtxtFormacaoMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJtxtFormacaoMslActionPerformed

    private void jFmtCepMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCepMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCepMslActionPerformed

    private void jFmtDataMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataMslActionPerformed

    private void jJtxtEstadoCivilMslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJtxtEstadoCivilMslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJtxtEstadoCivilMslActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCliente dialog = new JDlgCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtCidadeMsl;
    private javax.swing.JFormattedTextField JTxtEmailMsl;
    private javax.swing.JTextField JTxtEnderecoMsl;
    private javax.swing.JTextField JTxtEstadoMsl;
    private javax.swing.JTextField JTxtProfissaoMsl;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JFormattedTextField jFmtCepMsl;
    private javax.swing.JFormattedTextField jFmtCpfMsl;
    private javax.swing.JFormattedTextField jFmtDataMsl;
    private javax.swing.JFormattedTextField jFmtRgMsl;
    private javax.swing.JFormattedTextField jFmtTelefoneMsl;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jJtxtEstadoCivilMsl;
    private javax.swing.JFormattedTextField jJtxtFormacaoMsl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtCodigoMsl;
    private javax.swing.JTextField jTxtNomeMsl;
    // End of variables declaration//GEN-END:variables
}
