/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



/**
 *
 * @author Sebas :0
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Principal");
        setExtendedState(MAXIMIZED_BOTH);//quando esta tudo em maiusculo em C e uma constante
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal_msl = new javax.swing.JMenu();
        jMnuClientes_msl = new javax.swing.JMenuItem();
        jMnuUsuarios_msl = new javax.swing.JMenuItem();
        jMnuProduto_msl = new javax.swing.JMenuItem();
        jMnuVendedor_msl = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair_msl = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas_msl = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jMnuPrincipal_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pasta-16.png"))); // NOI18N
        jMnuPrincipal_msl.setMnemonic('P');
        jMnuPrincipal_msl.setText("Principal");
        jMnuPrincipal_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPrincipal_mslActionPerformed(evt);
            }
        });

        jMnuClientes_msl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cliente.png"))); // NOI18N
        jMnuClientes_msl.setMnemonic('C');
        jMnuClientes_msl.setText("Clientes");
        jMnuClientes_msl.setToolTipText("");
        jMnuClientes_msl.setAutoscrolls(true);
        jMnuClientes_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientes_mslActionPerformed(evt);
            }
        });
        jMnuPrincipal_msl.add(jMnuClientes_msl);

        jMnuUsuarios_msl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Usuario.png"))); // NOI18N
        jMnuUsuarios_msl.setMnemonic('U');
        jMnuUsuarios_msl.setText("Usuários");
        jMnuUsuarios_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios_mslActionPerformed(evt);
            }
        });
        jMnuPrincipal_msl.add(jMnuUsuarios_msl);

        jMnuProduto_msl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProduto_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Produto.png"))); // NOI18N
        jMnuProduto_msl.setMnemonic('C');
        jMnuProduto_msl.setText("Produto");
        jMnuProduto_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProduto_mslActionPerformed(evt);
            }
        });
        jMnuPrincipal_msl.add(jMnuProduto_msl);

        jMnuVendedor_msl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Funcionario.png"))); // NOI18N
        jMnuVendedor_msl.setText("Funcionario");
        jMnuVendedor_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedor_mslActionPerformed(evt);
            }
        });
        jMnuPrincipal_msl.add(jMnuVendedor_msl);
        jMnuPrincipal_msl.add(jSeparator1);

        jMnuSair_msl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar .png"))); // NOI18N
        jMnuSair_msl.setMnemonic('S');
        jMnuSair_msl.setText("Sair");
        jMnuSair_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSair_mslActionPerformed(evt);
            }
        });
        jMnuPrincipal_msl.add(jMnuSair_msl);

        jMenuBar1.add(jMnuPrincipal_msl);

        jMnuMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-assistente-16.png"))); // NOI18N
        jMnuMovimento.setMnemonic('M');
        jMnuMovimento.setText("Movimento");

        jMnuVendas_msl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas_msl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Funcionario.png"))); // NOI18N
        jMnuVendas_msl.setText("Vendas");
        jMnuVendas_msl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendas_mslActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas_msl);

        jMenuBar1.add(jMnuMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientes_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientes_mslActionPerformed
        // TODO add your handling code here:
        
        JDlgClientes jDlgClientes = new JDlgClientes(null, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientes_mslActionPerformed

    private void jMnuUsuarios_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios_mslActionPerformed
        // TODO add your handling code here: 
        //cria um novo objeto jDlgUsuarios da classe JDlgUsuarios(maiusculo no comeco é classe, minusculo é objeto)
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarios_mslActionPerformed

                           
    private void jMnuPrincipal_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPrincipal_mslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuPrincipal_mslActionPerformed

    private void jMnuSair_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSair_mslActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSair_mslActionPerformed

    private void jMnuProduto_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProduto_mslActionPerformed
        // TODO add your handling code here:
        
        JDlgProdutoNovoIA jDlgProdutoNovoIA = new JDlgProdutoNovoIA(null, true);
        jDlgProdutoNovoIA.setVisible(true);
    }//GEN-LAST:event_jMnuProduto_mslActionPerformed

    private void jMnuVendedor_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedor_mslActionPerformed
        // TODO add your handling code here:
        JDlgFuncionarioNovoIA jDlgFuncionarioNovoIA = new JDlgFuncionarioNovoIA(null, true);
        jDlgFuncionarioNovoIA.setVisible(true);
    }//GEN-LAST:event_jMnuVendedor_mslActionPerformed

    private void jMnuVendas_mslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendas_mslActionPerformed
        // TODO add your handling code here:
        JDlgVendasProdutos jDlgVendasProdutos = new JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setVisible(true);
        
    }//GEN-LAST:event_jMnuVendas_mslActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(null, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JDlgProdutoNovoIA jDlgProdutoNovoIA = new JDlgProdutoNovoIA(null, true);
        jDlgProdutoNovoIA.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //ou
        //System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JDlgVendasProdutos jDlgVendasProdutos = new JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuClientes_msl;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenu jMnuPrincipal_msl;
    private javax.swing.JMenuItem jMnuProduto_msl;
    private javax.swing.JMenuItem jMnuSair_msl;
    private javax.swing.JMenuItem jMnuUsuarios_msl;
    private javax.swing.JMenuItem jMnuVendas_msl;
    private javax.swing.JMenuItem jMnuVendedor_msl;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
