package bean;
// Generated 31/07/2024 09:26:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteMsl generated by hbm2java
 */
@Entity
@Table(name="clienteMsl"
    ,catalog="db_mario_lira"
)
public class ClienteMsl  implements java.io.Serializable {


     private int idclienteMsl;
     private String nomeMsl;
     private String emailMsl;
     private String telefoneMsl;
     private String estadoCivilMsl;
     private String profissaoMsl;
     private String rgMsl;
     private String cpfMsl;
     private Date dataNascMsl;
     private String enderecoMsl;
     private String estadoMsl;
     private String cidadeMsl;
     private String cepMsl;
     private Date dataRegistroMsl;
     private String formacaoMsl;
     private Set vendasMsls = new HashSet(0);

    public ClienteMsl() {
    }

	
    public ClienteMsl(int idclienteMsl, String nomeMsl, String emailMsl, String telefoneMsl, String estadoCivilMsl, String profissaoMsl, String rgMsl, String cpfMsl, Date dataNascMsl, String enderecoMsl, String estadoMsl, String cidadeMsl, String cepMsl, Date dataRegistroMsl, String formacaoMsl) {
        this.idclienteMsl = idclienteMsl;
        this.nomeMsl = nomeMsl;
        this.emailMsl = emailMsl;
        this.telefoneMsl = telefoneMsl;
        this.estadoCivilMsl = estadoCivilMsl;
        this.profissaoMsl = profissaoMsl;
        this.rgMsl = rgMsl;
        this.cpfMsl = cpfMsl;
        this.dataNascMsl = dataNascMsl;
        this.enderecoMsl = enderecoMsl;
        this.estadoMsl = estadoMsl;
        this.cidadeMsl = cidadeMsl;
        this.cepMsl = cepMsl;
        this.dataRegistroMsl = dataRegistroMsl;
        this.formacaoMsl = formacaoMsl;
    }
    public ClienteMsl(int idclienteMsl, String nomeMsl, String emailMsl, String telefoneMsl, String estadoCivilMsl, String profissaoMsl, String rgMsl, String cpfMsl, Date dataNascMsl, String enderecoMsl, String estadoMsl, String cidadeMsl, String cepMsl, Date dataRegistroMsl, String formacaoMsl, Set vendasMsls) {
       this.idclienteMsl = idclienteMsl;
       this.nomeMsl = nomeMsl;
       this.emailMsl = emailMsl;
       this.telefoneMsl = telefoneMsl;
       this.estadoCivilMsl = estadoCivilMsl;
       this.profissaoMsl = profissaoMsl;
       this.rgMsl = rgMsl;
       this.cpfMsl = cpfMsl;
       this.dataNascMsl = dataNascMsl;
       this.enderecoMsl = enderecoMsl;
       this.estadoMsl = estadoMsl;
       this.cidadeMsl = cidadeMsl;
       this.cepMsl = cepMsl;
       this.dataRegistroMsl = dataRegistroMsl;
       this.formacaoMsl = formacaoMsl;
       this.vendasMsls = vendasMsls;
    }
   
     @Id 

    
    @Column(name="idclienteMsl", unique=true, nullable=false)
    public int getIdclienteMsl() {
        return this.idclienteMsl;
    }
    
    public void setIdclienteMsl(int idclienteMsl) {
        this.idclienteMsl = idclienteMsl;
    }

    
    @Column(name="nomeMsl", nullable=false, length=45)
    public String getNomeMsl() {
        return this.nomeMsl;
    }
    
    public void setNomeMsl(String nomeMsl) {
        this.nomeMsl = nomeMsl;
    }

    
    @Column(name="emailMsl", nullable=false, length=45)
    public String getEmailMsl() {
        return this.emailMsl;
    }
    
    public void setEmailMsl(String emailMsl) {
        this.emailMsl = emailMsl;
    }

    
    @Column(name="telefoneMsl", nullable=false, length=15)
    public String getTelefoneMsl() {
        return this.telefoneMsl;
    }
    
    public void setTelefoneMsl(String telefoneMsl) {
        this.telefoneMsl = telefoneMsl;
    }

    
    @Column(name="estadoCivilMsl", nullable=false, length=20)
    public String getEstadoCivilMsl() {
        return this.estadoCivilMsl;
    }
    
    public void setEstadoCivilMsl(String estadoCivilMsl) {
        this.estadoCivilMsl = estadoCivilMsl;
    }

    
    @Column(name="profissaoMsl", nullable=false, length=20)
    public String getProfissaoMsl() {
        return this.profissaoMsl;
    }
    
    public void setProfissaoMsl(String profissaoMsl) {
        this.profissaoMsl = profissaoMsl;
    }

    
    @Column(name="rgMsl", nullable=false, length=14)
    public String getRgMsl() {
        return this.rgMsl;
    }
    
    public void setRgMsl(String rgMsl) {
        this.rgMsl = rgMsl;
    }

    
    @Column(name="cpfMsl", nullable=false, length=15)
    public String getCpfMsl() {
        return this.cpfMsl;
    }
    
    public void setCpfMsl(String cpfMsl) {
        this.cpfMsl = cpfMsl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascMsl", nullable=false, length=10)
    public Date getDataNascMsl() {
        return this.dataNascMsl;
    }
    
    public void setDataNascMsl(Date dataNascMsl) {
        this.dataNascMsl = dataNascMsl;
    }

    
    @Column(name="enderecoMsl", nullable=false, length=45)
    public String getEnderecoMsl() {
        return this.enderecoMsl;
    }
    
    public void setEnderecoMsl(String enderecoMsl) {
        this.enderecoMsl = enderecoMsl;
    }

    
    @Column(name="estadoMsl", nullable=false, length=20)
    public String getEstadoMsl() {
        return this.estadoMsl;
    }
    
    public void setEstadoMsl(String estadoMsl) {
        this.estadoMsl = estadoMsl;
    }

    
    @Column(name="cidadeMsl", nullable=false, length=30)
    public String getCidadeMsl() {
        return this.cidadeMsl;
    }
    
    public void setCidadeMsl(String cidadeMsl) {
        this.cidadeMsl = cidadeMsl;
    }

    
    @Column(name="cepMsl", nullable=false, length=15)
    public String getCepMsl() {
        return this.cepMsl;
    }
    
    public void setCepMsl(String cepMsl) {
        this.cepMsl = cepMsl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataRegistroMsl", nullable=false, length=10)
    public Date getDataRegistroMsl() {
        return this.dataRegistroMsl;
    }
    
    public void setDataRegistroMsl(Date dataRegistroMsl) {
        this.dataRegistroMsl = dataRegistroMsl;
    }

    
    @Column(name="formacaoMsl", nullable=false, length=45)
    public String getFormacaoMsl() {
        return this.formacaoMsl;
    }
    
    public void setFormacaoMsl(String formacaoMsl) {
        this.formacaoMsl = formacaoMsl;
    }




}


