package bean;
// Generated 31/07/2024 09:26:21 AM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuncionarioMsl generated by hbm2java
 */
@Entity
@Table(name="funcionarioMsl"
    ,catalog="db_mario_lira"
)
public class FuncionarioMsl  implements java.io.Serializable {


     private int idfuncionarioMsl;
     private String nomeMsl;
     private String emailMsl;
     private String numeroTelefoneMsl;
     private String cpfMsl;
     private String departamentoMsl;
     private String informacoesMsl;
     private double salarioMsl;
     private Set vendasMsls = new HashSet(0);

    public FuncionarioMsl() {
    }

	
    public FuncionarioMsl(int idfuncionarioMsl, String nomeMsl, String emailMsl, String numeroTelefoneMsl, String cpfMsl, String departamentoMsl, String informacoesMsl, double salarioMsl) {
        this.idfuncionarioMsl = idfuncionarioMsl;
        this.nomeMsl = nomeMsl;
        this.emailMsl = emailMsl;
        this.numeroTelefoneMsl = numeroTelefoneMsl;
        this.cpfMsl = cpfMsl;
        this.departamentoMsl = departamentoMsl;
        this.informacoesMsl = informacoesMsl;
        this.salarioMsl = salarioMsl;
    }
    public FuncionarioMsl(int idfuncionarioMsl, String nomeMsl, String emailMsl, String numeroTelefoneMsl, String cpfMsl, String departamentoMsl, String informacoesMsl, double salarioMsl, Set vendasMsls) {
       this.idfuncionarioMsl = idfuncionarioMsl;
       this.nomeMsl = nomeMsl;
       this.emailMsl = emailMsl;
       this.numeroTelefoneMsl = numeroTelefoneMsl;
       this.cpfMsl = cpfMsl;
       this.departamentoMsl = departamentoMsl;
       this.informacoesMsl = informacoesMsl;
       this.salarioMsl = salarioMsl;
       this.vendasMsls = vendasMsls;
    }
   
     @Id 

    
    @Column(name="idfuncionarioMsl", unique=true, nullable=false)
    public int getIdfuncionarioMsl() {
        return this.idfuncionarioMsl;
    }
    
    public void setIdfuncionarioMsl(int idfuncionarioMsl) {
        this.idfuncionarioMsl = idfuncionarioMsl;
    }

    
    @Column(name="nomeMsl", nullable=false, length=45)
    public String getNomeMsl() {
        return this.nomeMsl;
    }
    
    public void setNomeMsl(String nomeMsl) {
        this.nomeMsl = nomeMsl;
    }

    
    @Column(name="emailMsl", nullable=false, length=45)
    public String getEmailMsl() {
        return this.emailMsl;
    }
    
    public void setEmailMsl(String emailMsl) {
        this.emailMsl = emailMsl;
    }

    
    @Column(name="numeroTelefoneMsl", nullable=false, length=14)
    public String getNumeroTelefoneMsl() {
        return this.numeroTelefoneMsl;
    }
    
    public void setNumeroTelefoneMsl(String numeroTelefoneMsl) {
        this.numeroTelefoneMsl = numeroTelefoneMsl;
    }

    
    @Column(name="cpfMsl", nullable=false, length=11)
    public String getCpfMsl() {
        return this.cpfMsl;
    }
    
    public void setCpfMsl(String cpfMsl) {
        this.cpfMsl = cpfMsl;
    }

    
    @Column(name="departamentoMsl", nullable=false, length=45)
    public String getDepartamentoMsl() {
        return this.departamentoMsl;
    }
    
    public void setDepartamentoMsl(String departamentoMsl) {
        this.departamentoMsl = departamentoMsl;
    }

    
    @Column(name="informacoesMsl", nullable=false, length=45)
    public String getInformacoesMsl() {
        return this.informacoesMsl;
    }
    
    public void setInformacoesMsl(String informacoesMsl) {
        this.informacoesMsl = informacoesMsl;
    }

    
    @Column(name="salarioMsl", nullable=false, precision=9)
    public double getSalarioMsl() {
        return this.salarioMsl;
    }
    
    public void setSalarioMsl(double salarioMsl) {
        this.salarioMsl = salarioMsl;
    }




}


