package bean;
// Generated 31/07/2024 09:26:21 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoVendaMsl generated by hbm2java
 */
@Entity
@Table(name="produtoVendaMsl"
    ,catalog="db_mario_lira"
)
public class ProdutoVendaMsl  implements java.io.Serializable {


     private int idprodutoVendaMsl;
     private ProdutoMsl produtoMsl;
     private VendasMsl vendasMsl;
     private int quantidadeMsl;
     private int valorUnitarioMsl;

    public ProdutoVendaMsl() {
    }

    public ProdutoVendaMsl(int idprodutoVendaMsl, ProdutoMsl produtoMsl, VendasMsl vendasMsl, int quantidadeMsl, int valorUnitarioMsl) {
       this.idprodutoVendaMsl = idprodutoVendaMsl;
       this.produtoMsl = produtoMsl;
       this.vendasMsl = vendasMsl;
       this.quantidadeMsl = quantidadeMsl;
       this.valorUnitarioMsl = valorUnitarioMsl;
    }
   
     @Id 

    
    @Column(name="idprodutoVendaMsl", unique=true, nullable=false)
    public int getIdprodutoVendaMsl() {
        return this.idprodutoVendaMsl;
    }
    
    public void setIdprodutoVendaMsl(int idprodutoVendaMsl) {
        this.idprodutoVendaMsl = idprodutoVendaMsl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtoMsl", nullable=false)
    public ProdutoMsl getProdutoMsl() {
        return this.produtoMsl;
    }
    
    public void setProdutoMsl(ProdutoMsl produtoMsl) {
        this.produtoMsl = produtoMsl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendasMsl", nullable=false)
    public VendasMsl getVendasMsl() {
        return this.vendasMsl;
    }
    
    public void setVendasMsl(VendasMsl vendasMsl) {
        this.vendasMsl = vendasMsl;
    }

    
    @Column(name="quantidadeMsl", nullable=false)
    public int getQuantidadeMsl() {
        return this.quantidadeMsl;
    }
    
    public void setQuantidadeMsl(int quantidadeMsl) {
        this.quantidadeMsl = quantidadeMsl;
    }

    
    @Column(name="valorUnitarioMsl", nullable=false)
    public int getValorUnitarioMsl() {
        return this.valorUnitarioMsl;
    }
    
    public void setValorUnitarioMsl(int valorUnitarioMsl) {
        this.valorUnitarioMsl = valorUnitarioMsl;
    }




}


