package bean;
// Generated 28/08/2024 10:55:43 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasMsl generated by hbm2java
 */
@Entity
@Table(name="vendasMsl"
    ,catalog="db_mario_lira"
)
public class VendasMsl  implements java.io.Serializable {


     private int idvendaMsl;
     private ClienteMsl clienteMsl;
     private FuncionarioMsl funcionarioMsl;
     private Date dataVendasMsl;
     private double valorTotalMsl;
     

    public VendasMsl() {
    }

	
    public VendasMsl(int idvendaMsl, ClienteMsl clienteMsl, FuncionarioMsl funcionarioMsl, Date dataVendasMsl, double valorTotalMsl) {
        this.idvendaMsl = idvendaMsl;
        this.clienteMsl = clienteMsl;
        this.funcionarioMsl = funcionarioMsl;
        this.dataVendasMsl = dataVendasMsl;
        this.valorTotalMsl = valorTotalMsl;
    }
   
   
     @Id 

    
    @Column(name="IdvendaMsl", unique=true, nullable=false)
    public int getIdvendaMsl() {
        return this.idvendaMsl;
    }
    
    public void setIdvendaMsl(int idvendaMsl) {
        this.idvendaMsl = idvendaMsl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clienteMsl", nullable=false)
    public ClienteMsl getClienteMsl() {
        return this.clienteMsl;
    }
    
    public void setClienteMsl(ClienteMsl clienteMsl) {
        this.clienteMsl = clienteMsl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionarioMsl", nullable=false)
    public FuncionarioMsl getFuncionarioMsl() {
        return this.funcionarioMsl;
    }
    
    public void setFuncionarioMsl(FuncionarioMsl funcionarioMsl) {
        this.funcionarioMsl = funcionarioMsl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVendasMsl", nullable=false, length=10)
    public Date getDataVendasMsl() {
        return this.dataVendasMsl;
    }
    
    public void setDataVendasMsl(Date dataVendasMsl) {
        this.dataVendasMsl = dataVendasMsl;
    }

    
    @Column(name="valorTotalMsl", nullable=false, precision=9)
    public double getValorTotalMsl() {
        return this.valorTotalMsl;
    }
    
    public void setValorTotalMsl(double valorTotalMsl) {
        this.valorTotalMsl = valorTotalMsl;
    }





}


